### ISSUE TITLE
WheelSpeeds who is right?

### ISSUE THREAD

**Issue by rusefillc** [HeinrichG-V12/E65_ReverseEngineering#3]
opendbc says 0.0643699 factor at https://github.com/commaai/opendbc/blob/a604b15617a1fcad914f10b7f4430dbcf080708a/bmw_e9x_e8x.dbc#L93

we say 0.0625 at https://github.com/HeinrichG-V12/E65_ReverseEngineering/blob/main/docs/0x0CE.md

would that mean that one of the repos is not exactly right?

**Comment by rusefillc** [comment]
@dzid26 FYI

**Comment by dzid26** [comment]
Yours must be right. 
I think I obtained that by comparing to cruise control target.

**Comment by HeinrichG-V12** [comment]
1. These definitions of the messages and signals **come from Bosch**, are these to be considered correct.
2. These definitions refer to and apply to an E65/E66. It may well be that it is different for other series, this is **ONLY** about an E65/E66.
